elearning/urls.py
import django.contrib.auth.views as auth_views
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from .course import views as course_views


urlpatterns = [
    # /
    url(r'^$', views.index, name='index'),

    # See https://docs.djangoproject.com/en/1.8/topics/auth/default/#module-django.contrib.auth.views
    # url(r'^', include('django.contrib.auth.urls')),
    url(r'^login/', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/', auth_views.logout, {'template_name': 'registration/logout.html'}, name='logout'),

    # /admin
    url(r'^admin/', include(admin.site.urls)),

    # /course
    url(r'^course/add-course/', course_views.add_course, name='add_course'),
    url(r'^course/see-courses/', course_views.see_courses, name='see_courses'),
    url(r'^course/see-assignments/(?P<id>[-\w]+)/$', course_views.see_assignments, name='see_assignments'),
    url(r'^course/add-assignment/(?P<id>[-\w]+)/$', course_views.add_assignment, name='add_assignment'),
    url(r'^course/give_assignment_to_students/([-\w]+)/$', course_views.give_assignment_to_students, name="give_assignment_to_students"),
    url(r'^course/give_assignment_to_groups/([-\w]+)/$', course_views.give_assignment_to_groups, name="give_assignment_to_groups"),
    # /schedule
    url(r'^schedule/', include('schedule.urls')),

    # /forum
    url(r'^forums/', include('pybb.urls', namespace='pybb'))

] + staticfiles_urlpatterns()

elearning/course/forms.py
from django import forms
from django.contrib.admin import widgets
from django.db.models.query_utils import Q
from django.forms.extras.widgets import SelectDateWidget
from django.forms.widgets import HiddenInput, Textarea, DateInput
from django.forms import ModelForm, CheckboxSelectMultiple
from django.contrib.auth.models import Group
from elearning.models import Course, Subject,UserELearning, Assignment, AssignmentGroup


# https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/
class SubjectModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name


class TeacherModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.id+obj.name


class SimpleCourseForm(ModelForm):
    class Meta:
        model = Course
        fields = ['name']
    subject = SubjectModelChoiceField(queryset=Subject.objects.all(), empty_label=None)


class TeacherEditCourseForm(SimpleCourseForm):
    students = forms.ModelMultipleChoiceField(required=False, widget=CheckboxSelectMultiple, queryset=UserELearning.objects.filter(user__groups__name='student'))
    assistants = forms.ModelMultipleChoiceField(required=False, widget=CheckboxSelectMultiple, queryset=UserELearning.objects.filter(user__groups__name='assistant'))

    def clean_students(self):
        data = self.cleaned_data['students']
        return data

    def clean_assistants(self):
        data = self.cleaned_data['assistants']
        return data


class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ['name', 'description', 'deadline', 'type', 'group']

        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 7}),
            'deadline': SelectDateWidget(
                empty_label=("Choose Year", "Choose Month", "Choose Day"),
                ),
        }
    id = forms.HiddenInput()
    group = forms.ModelChoiceField(required=True, queryset=AssignmentGroup.objects.all(), empty_label=None)


class ReadOnlyAssignmentForm(AssignmentForm):

    def __init__(self, *args, **kwargs):
        super(AssignmentForm, self).__init__(*args, **kwargs)
        for key in self.fields.keys():
            self.fields[key].widget.attrs['readonly'] = True
            self.fields[key].widget.attrs['disabled'] = 'disabled'
        widgets = {
            'deadline': forms.CharField(),
        }


class AssignStudentsForm(forms.Form):

    def __init__(self, assignment, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        self.fields["students"] = forms.ModelMultipleChoiceField(required=False, widget=CheckboxSelectMultiple,
                                              queryset=assignment.course.students.all())

    def clean_students(self):
        data = self.cleaned_data['students']
        return data


class AdminEditCourseForm(TeacherEditCourseForm):
    teacher = forms.ModelChoiceField(required=True, queryset=UserELearning.objects.filter(user__groups__name='teacher'), empty_label=None)

elearning/course/views.py
#!/usr/bin/python
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q
from django.forms import modelformset_factory
from django.shortcuts import render, redirect

from elearning.course.forms import SimpleCourseForm, AdminEditCourseForm, TeacherEditCourseForm, AssignmentForm, \
    ReadOnlyAssignmentForm, AssignStudentsForm
from elearning.models import Enrollment, Course, AssistantCourse, Assignment, StudentAssignment
from elearning.utils import get_current_user, create_forums_course


@login_required
def add_course(request):
    if request.method == 'POST':
        user = get_current_user(request)
        form = SimpleCourseForm(request.POST)
        if form.is_valid():
            course = Course.objects.create(name=form.cleaned_data['name'], subject=form.cleaned_data['subject'],
                                           teacher=user)
            create_forums_course(course)

            messages.success(request, "Course created")
            return redirect('index')
    else:
        form = SimpleCourseForm()

    return render(request, 'course/add_course.html', {'form': form})


@login_required
@user_passes_test(lambda u: u.groups.filter(name__in=['assistant', 'teacher']).exists())
def add_assignment(request, id):
    if request.method == "POST":
        form = AssignmentForm(request.POST)
        if form.is_valid():
            assignment = form.save(commit=False)
            assignment.course = Course.objects.get(id=id)
            assignment.save()
            messages.success(request, "Assignment created")
        else:
            messages.error(request, "Assignment not created")
        return redirect('index')
    else:
        course = Course.objects.get(id=id)
        user = get_current_user(request)
        if course.teacher != user and user not in course.assistants.all():
            messages.error(request, "You are not allowed to add an assignment to this course.")
            return redirect('index')
        form = AssignmentForm()
        return render(request, 'course/add_assignment.html', {'form': form, 'course': course})


@login_required
@user_passes_test(lambda u: u.groups.filter(name__in=['admin', 'teacher']).exists())
def see_courses(request):
    user = get_current_user(request)
    user_is_admin = request.user.groups.filter(name='admin').exists()
    can_delete = True if user_is_admin else False
    used_form = AdminEditCourseForm if user_is_admin else TeacherEditCourseForm
    if user_is_admin:
        CourseFormSet = modelformset_factory(Course, fields=('name', 'subject', 'teacher', 'assistants', 'students'),
                                             can_delete=can_delete, form=used_form, max_num=1)
    else:
        CourseFormSet = modelformset_factory(Course, fields=('name', 'subject', 'assistants', 'students'),
                                             can_delete=can_delete, form=used_form, max_num=1)
    if request.method == 'POST':
        formset = CourseFormSet(request.POST, request.FILES)
        if user_is_admin:
            if formset.is_valid():
                for form in formset:
                    course = form.save(commit=False)
                    # TODO get rid of this UGLY WAY
                    Enrollment.objects.filter(course=course).delete()
                    for student in form.clean_students():
                        Enrollment.objects.create(user=student, course=course)
                    AssistantCourse.objects.filter(course=course).delete()
                    for assistant in form.clean_assistants():
                        AssistantCourse.objects.create(user=assistant, course=course)
                    course.save()
                messages.success(request, "Courses successfully edited.")
            else:
                messages.error(request, str(formset.errors))
            return redirect('index')
        else:
            if formset.is_valid():
                for form in formset:
                    course = form.save(commit=False)
                    course.teacher = user
                    Enrollment.objects.filter(course=course).delete()
                    for student in form.clean_students():
                        Enrollment.objects.create(user=student, course=course)
                    AssistantCourse.objects.filter(course=course).delete()
                    for assistant in form.clean_assistants():
                        AssistantCourse.objects.create(user=assistant, course=course)
                    course.save()
                messages.success(request, "Courses successfully edited.")
            else:
                messages.error(request, str(formset.errors))

            return redirect('index')
    else:
        if user_is_admin:
            formset = CourseFormSet(queryset=Course.objects.all())
        else:
            formset = CourseFormSet(queryset=Course.objects.filter(teacher=user))
    return render(request, 'course/see_courses.html', {'formset': formset})


@login_required
def see_assignments(request, id):
    user = get_current_user(request)
    course = Course.objects.get(id=id)
    can_delete = True if user == course.teacher or user in course.assistants.all() else False
    AssignmentFormSet = modelformset_factory(Assignment,
                                             fields=('id', 'name', 'description', 'deadline', 'type', 'group'),
                                             can_delete=can_delete, form=AssignmentForm, max_num=0)
    if request.method == 'POST':
        formset = AssignmentFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            messages.success(request, "Assignments successfully saved.")
        return redirect('index')
    else:
        if user.is_in_group("student"):
            AssignmentFormSet.form = ReadOnlyAssignmentForm
            formset = AssignmentFormSet(queryset=Assignment.objects.filter(Q(students__user=request.user) and
                                                                           Q(course=course)).all())
        else:
            formset = AssignmentFormSet(queryset=Assignment.objects.filter(course=course).all())
    if len(formset) == 0:
        messages.info(request, "There are no assignments for this course")
        return redirect('index')
    else:
        return render(request, 'course/see_assignments.html',
                      {'formset': formset, 'course': course, 'user_elearning': user})


@login_required()
def give_assignment_to_students(request, assignment_id):
    if request.method == "POST":
        assignment = Assignment.objects.get(id=assignment_id)
        form = AssignStudentsForm(assignment, request.POST, request.FILES)
        if form.is_valid():
            for student in form.clean_students():
                StudentAssignment.objects.get_or_create(user=student, assignment=assignment, grade=0)
            messages.success(request, "Assignment successfully given.")
            return redirect('index')
    else:
        assignment = Assignment.objects.get(id=assignment_id)
        form = AssignStudentsForm(assignment)
    return render(request, 'course/give_assignment_to_students.html', {'form': form, 'id': assignment_id})


# TODO
@login_required()
def give_assignment_to_groups(request, assignment_id):
    if request.method == "POST":
        pass
    else:
        messages.info(request, 'There are no available groups.')
    return redirect('index')

elearning/views.py
#!/usr/bin/python
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.template.context import RequestContext


from elearning.models import Enrollment, UserELearning, Course
from elearning.utils import get_current_user


@login_required
def index(request):
    user = get_current_user(request)

    if user.is_student():
        courses = Course.objects.filter(students__user=request.user).all()
        # enrollments = Enrollment.objects.filter(user=user).all()
        # courses = []
        # for e in enrollments:
        #     courses.append((e.course, e.enroll_date))
    elif user.is_teacher():
        courses = Course.objects.filter(teacher=user).all()
    elif user.is_assistant():
        courses = Course.objects.filter(assistants__user=request.user).all()
    else:
        courses = Course.objects.all()

    rc = RequestContext(request, {
        "user_elearning": user,
        "courses": courses
    })
    return render(request, 'index.html', context_instance=rc)

elearning/templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}
{% load url from future %}
{% load i18n pybb_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}eLearning App{% endblock %}</title>
    {% if  '/forums' in request.path %}
        <link rel="stylesheet" href="{% static 'elearning/css/bootstrap2.min.css' %}">
    {% else %}
        {% bootstrap_css %}
    {% endif %}

    {# For forum #}
    {% block extra_head %}{% endblock %}
    {% block extra_style %}{% endblock %}

    <!-- Compiled and minified CSS -->

    <link rel="stylesheet" href="{% static 'elearning/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'elearning/css/responsive.css' %}">

    {% block head %}{% endblock %}
</head>
<body {% block body_attributes %}{% endblock %}>

{% if user.is_authenticated %}
    {% include 'partials/_header.html' %}
{% endif %}

<div class="container-fluid">
    {# Display flash messages #}
    {% if messages %}
        <hr>
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
        <hr>
    {% endif %}

    {# For forum #}
    {% block breadcrumb %}{% endblock %}

    {% block body %}{% endblock %}

    {# For forum #}
    {% block content %}{% endblock %}

</div>

<!-- Compiled and minified JavaScript -->
{% bootstrap_javascript %}
<script type="text/javascript" src="{% static 'pybb/js/pybbjs.js' %}"></script>
<script type="text/javascript" src="{% static 'pybb/js/jquery.formset.min.js' %}"></script>
{% block extra_script %}{% endblock %}
<script src="{% static 'elearning/js/base.js' %}"></script>
<script src="{% static 'elearning/js/vendors/sb-admin-2.js' %}"></script>

{#{% if  '/forums' in request.path %}#}
{#    <script>#}
{#        console.log("outside");#}
{##}
{#        $(document).ready(function () {#}
{#            console.log("foreach");#}
{#            $('img').each(function () {#}
{#                var href = $(this).attr('src');#}
{#                if (href.startsWith("pybb")) {#}
{#                    $(this).attr('href', "http://127.0.0.1:8000/static" + href);#}
{#                }#}
{#            });#}
{#        });#}
{##}
{#    </script>#}
{#{% endif %}#}
</body>
</html>

elearning/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load scheduletags %}

{% block body %}
    {% if user.is_authenticated %}
    <style>
        body {
            background-image: url(/static/elearning/images/background.jpg);
            background-size: cover;
            background-position: center top;
        }
        #page-wrapper {
            margin: 0 !important;
        }
    </style>
    <link rel="stylesheet" href="{% static 'elearning/css/sb-admin-2.css' %}">
    <link rel="stylesheet" href="{% static 'elearning/css/timeline.css' %}">
    <div id="wrapper">

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><p>Hi {{ user.first_name }} ({{ user.username }})</a></p></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                {% if user_elearning.is_student %}
                    
                {% elif user_elearning.is_teacher or user_elearning.is_assistant %}
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-comments fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">ADD</div>
                                        <div>New</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'add_course' %}">
                                <div class="panel-footer">
                                    <span class="pull-left">Course</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-comments fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">EDIT</div>
                                        <div>Courses</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'see_courses' %}">
                                <div class="panel-footer">
                                    <span class="pull-left">Click here</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                {% elif user_elearning.is_admin %}
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-comments fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">EDIT</div>
                                        <div>Courses</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'see_courses' %}">
                                <div class="panel-footer">
                                    <span class="pull-left">Click here</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-comments fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">Admin</div>
                                        <div>Area</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'admin:index' %}">
                                <div class="panel-footer">
                                    <span class="pull-left">Click here</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-comments fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">Forums</div>
                                        <div>Area</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'pybb:index' %}">
                                <div class="panel-footer">
                                    <span class="pull-left">Click here</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endif %}
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                {% if user_elearning.is_student %}
                    <div class="panel panel-default">
                        <div class="panel-heading">Courses table
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-hover table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Course Name</th>
                                                    <th>Teacher</th>
                                                    <th>Links</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for course in courses %}
                                                    <tr>
                                                        <td>{{ course.name }}</td>
                                                        <td>{{ course.teacher.user.first_name}} {{ course.teacher.user.last_name }}</td>
                                                        <td><a href="{% url 'see_assignments' course.id %}">Assignments</a></td>
                                                        <td><a href="{% url 'pybb:forum' course.get_forum_id %}">Forum/Discussion</a></td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- /.table-responsive -->
                                </div>
                                <!-- /.col-lg-12 (nested) -->
                            </div>
                            <!-- /.row -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                {% elif user_elearning.is_teacher or user_elearning.is_assistant %}
                    <div class="panel panel-default">
                        <div class="panel-heading">Courses table
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-hover table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Course Name</th>
                                                    <th>Subject</th>
                                                    <th>Links</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for course in courses %}
                                                    <tr>
                                                        <td>{{ course.name }}</td>
                                                        <td>{{ course.subject.name }}</td>
                                                        <td><a href="{% url 'see_assignments' course.id %}">Assignments</a></td>
                                                        <td><a href="{% url 'add_assignment' course.id %}">Add assignment</a></td>
                                                        <td><a href="{% url 'pybb:forum' course.get_forum_id %}">Forum/Discussion</a></td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- /.table-responsive -->
                                </div>
                                <!-- /.col-lg-12 (nested) -->
                            </div>
                            <!-- /.row -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                {% endif %}
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    {% else %}
        <p>Please <a href="{% url 'login' %}">login</a> to see this page.</p>
    {% endif %}
{% endblock %}

<script src="{% static 'elearning/js/vendors/sb-admin-2.js' %}"></script>